### ISSUE TITLE
Unable to build project on Node version 18 and above

### ISSUE THREAD

**Issue by TechhDan** [photonstorm/phaser3-project-template#100]
The project does not build on newer versions of node. I tried on Node version 18.12.1 and 19.1.0. I had to revert Node to LTS Gallium 16.18.1 for the project to build.
```
npm start

> phaser3-project-template@1.1.2 start
> webpack-dev-server --config webpack/base.js --open

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /var/www/html/games/demo
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/var/www/html/games/demo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/var/www/html/games/demo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:471:10)
    at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:503:5
    at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:358:12
    at /var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```

**Comment by firstygoldfish** [comment]
For reference, also an issue in 17

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
.
.
.
    at iterateNormalLoaders (/home/carl/game1/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/carl/game1/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.1

**Comment by john-farina** [comment]
Ran into the same issue, using nvm to install node v16.18.1 worked. Thanks!

**Comment by connorbrez** [comment]
Running into this issue as well

**Comment by jonathan-rose** [comment]
Also having this issue. Most of the advice you find online for resolving this suggests either downgrading to Node 16 or using legacy SSL ([for example](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)). These solutions are both insecure and a bit intimidating for newbies who might be coming to Phaser for the first time.

**Comment by elvisMat** [comment]
> The project does not build on newer versions of node. I tried on Node version 18.12.1 and 19.1.0. I had to revert Node to LTS Gallium 16.18.1 for the project to build.
> 
> ```
> npm start
> 
> > phaser3-project-template@1.1.2 start
> > webpack-dev-server --config webpack/base.js --open
> 
> ℹ ｢wds｣: Project is running at http://localhost:8080/
> ℹ ｢wds｣: webpack output is served from /
> ℹ ｢wds｣: Content not from webpack is served from /var/www/html/games/demo
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:71:19)
>     at Object.createHash (node:crypto:133:10)
>     at module.exports (/var/www/html/games/demo/node_modules/webpack/lib/util/createHash.js:135:53)
>     at NormalModule._initBuildHash (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:417:16)
>     at handleParseError (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:471:10)
>     at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:503:5
>     at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:358:12
>     at /var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
>     at iterateNormalLoaders (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
>     at iterateNormalLoaders (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
> node:internal/crypto/hash:71
>   this[kHandle] = new _Hash(algorithm, xofLen);
>                   ^
> 
> Error: error:0308010C:digital envelope routines::unsupported
>     at new Hash (node:internal/crypto/hash:71:19)
>     at Object.createHash (node:crypto:133:10)
>     at module.exports (/var/www/html/games/demo/node_modules/webpack/lib/util/createHash.js:135:53)
>     at NormalModule._initBuildHash (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:417:16)
>     at handleParseError (/var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:471:10)
>     at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:503:5
>     at /var/www/html/games/demo/node_modules/webpack/lib/NormalModule.js:358:12
>     at /var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
>     at iterateNormalLoaders (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
>     at Array.<anonymous> (/var/www/html/games/demo/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
>   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
>   library: 'digital envelope routines',
>   reason: 'unsupported',
>   code: 'ERR_OSSL_EVP_UNSUPPORTED'
> }
> 
> Node.js v18.12.1
> ```

 Has anyone found solution to this

**Comment by elvisMat** [comment]
> The fix without downgrading the node version is to run `npm install webpack@latest`
> 
> Then update the webpack-cli using the force tag `npm install webpack-cli@latest --force`
> 
> this worked with node 18.16.0 and npm 9.5.1

After following your instructions and run npm start i am faced with the issue

**Comment by SheW0lf** [comment]
I know this thread is a little stale, but to fix these issues, delete the `node_modules` folder if you already ran the install command, and delete the `package-lock.json` file, this is important! run `npm install` and then run `npm start` that should get things running. 

The reason this works is because the lock file is for "locking" down the versions defined in the `package.json` file, so when `npm install webpack-cli@latest --force` was run, none of the other packages got updated that are needed with the latest webpack. Deleting the lock file now allows all the carrots (^) on the versions in the `package.json` file to look for the newest version and will download them now that the lock file isn't forcing them to remain on the original versions defined there.

**Comment by ClementineAccount** [comment]
Doesn't work for me. I followed the steps a few times and I get
`Error: Cannot find module 'webpack-cli/bin/config-yargs'   `

> I know this thread is a little stale, but to fix these issues, delete the `node_modules` folder if you already ran the install command, and delete the `package-lock.json` file, this is important! run `npm install` and then run `npm start` that should get things running.
> 
> The reason this works is because the lock file is for "locking" down the versions defined in the `package.json` file, so when `npm install webpack-cli@latest --force` was run, none of the other packages got updated that are needed with the latest webpack. Deleting the lock file now allows all the carrots (^) on the versions in the `package.json` file to look for the newest version and will download them now that the lock file isn't forcing them to remain on the original versions defined there.

**Comment by photonstorm** [comment]
This is fixed with v2.0.0 of this template.

**Comment by firstygoldfish** [comment]
Thanks
